### ISSUE TITLE
方块9输入几个，方案就会用几个

### ISSUE THREAD

**Issue by cmcchai** [CmdBlockZQG/cbjq#1]
#### 简介：
方块9输入一个，所有方案用一个。
输入两个，所有方案用两个，并没提供1个方块9的方案。
输入三个，会出现卡顿。
输入四个以上，会出现无反应状态。

#### 重现步骤：
1. 输入行数：5。
2. 输入列数：6。
3. 摆放格子如下：
<img width="197" alt="Screenshot 2023-08-06 at 4 25 54 AM" src="https://github.com/CmdBlockZQG/cbjq/assets/76714924/ab3f85c2-2bc9-4374-ad46-b169ab861dfc">

4. 输入方块1个数：2。
5. 输入方块2个数：2。
6. 输入方块3个数：2。
7. 输入方块4个数：2。
8. 输入方块5个数：2。
9. 输入方块6个数：2。
10. 输入方块7个数：2。
11. 输入方块8个数：2。
12. 输入方块9个数：2。
13. 可见所有方案使用2个方块9。
<img width="210" alt="Screenshot 2023-08-06 at 3 51 00 AM" src="https://github.com/CmdBlockZQG/cbjq/assets/76714924/db5b7c54-ef41-4377-b576-a9218aa522f7">
<img width="223" alt="Screenshot 2023-08-06 at 4 16 45 AM" src="https://github.com/CmdBlockZQG/cbjq/assets/76714924/03f101cc-b860-4584-87e5-c66698d8d40b">

14. 已知方案存在使用1个方块9，但是步骤13.没提供1个方块9的方案。
<img width="232" alt="Screenshot 2023-08-06 at 4 45 56 AM" src="https://github.com/CmdBlockZQG/cbjq/assets/76714924/cf37c0fc-842c-4fc3-804e-f652eb18549e">

#### 严重程度：功能存在缺陷

**Comment by CmdBlockZQG** [comment]
我看了下 这个问题并不存在 输入2个里面仍然会有一个的方案只是你没翻到 比如140/2549

但是优先不用9这个是我想错了 方案是按照字典序排列的 后面用不用9取决于前面的填充方式 要达到优先不用9的效果可以枚举9方块的数量，从0开始逐步增加。对于每次枚举都进行完整搜索。这个方法目前可以在ui里手动进行
