### ISSUE TITLE
功能建议-没有完美方案的情况

### ISSUE THREAD

**Issue by tsctsc6** [CmdBlockZQG/cbjq#4]
现实中，完美方案显然十分难得。我们通常的操作是尽量拼，使剩下的格子尽量少，然后考虑用9号方块填补。
不知能否让程序“尽量拼”？

**Comment by CmdBlockZQG** [comment]
手动从小到大调整9号方块数量可以实现该效果。

**Comment by tsctsc6** [comment]
确实，如果可以的话，可以把当前方案拼剩下的各种方块数量以及总数量显示出来，方便看看能不能合成9号方块
